### ISSUE TITLE
CSS Style Rules werden nicht übernommen

### ISSUE THREAD

**Issue by nonnemann** [denadr/Web20App#30]
Wurde irgendwas geändert, so dass das nicht mehr läuft?

**Comment by denadr** [comment]
habe nur eine Orderstruktur erstellt und Dateien umbenannt (was wir für die html files noch machen sollten, aber da hab ich nicht mal durchgesehen wofür da mehrere index seiten und dann nochmal zusätzlich suchseiten sind^^). Dann habe ich natürlich die JS und Style referenzen dahingehend angepasst. hast du mal versucht sie wieder auf html Ebene zu ziehen? Vielleicht geht es dann wieder, dann müssen wir aber mal rausfinden, wie man auch Ordnerstrukturen benutzen kann...weil die sachen alle auf eine ebene hauen geht ja gar nicht :D

**Comment by denadr** [comment]
also nach 5 min googln: das web project wird in eine war datei gepackt... auf dem server müssen die Dateien daher über diese referenziert werden. in unserem fall: **/Web20/Styles/style.css**. Bei _Interaction_ auch. habe es mal ausprobiert und gepusht

http://stackoverflow.com/questions/8395941/in-eclipse-dynamic-web-project-how-to-link-css-to-jsp-file-in-webcontent-folder
